name: Build MODX Package

on:
  push:
    branches:
      - main
      - master

env:
  PHP_VERSION: '8.1'
  PACKAGE_NAME: 'yandexmaps-1.0.0-pl.transport.zip'
  PACKAGE_PATH: 'core/packages/${{ env.PACKAGE_NAME }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y php-cli unzip zip

      - name: Build the MODX package
        working-directory: _build
        run: |
          php build.transport.php

      - name: List package dir
        run: |
          echo "Looking for package at ${{ env.PACKAGE_PATH }}"
          ls -la core/packages || true

      - name: Upload built package as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: yandexmaps-package
          path: ${{ env.PACKAGE_PATH }}
          retention-days: 7